### ISSUE TITLE
logging error

### ISSUE THREAD

**Issue by mabhutidlodlo** [Skhendle/GraphQL_System#1]
unrecognised params

`......
    logging.basicConfig(filename='server.log', encoding='utf-8', level=logging.DEBUG)
  File "/home/sikhanyiso/anaconda3/lib/python3.7/logging/__init__.py", line 1916, in basicConfig
    raise ValueError('Unrecognised argument(s): %s' % keys)
ValueError: Unrecognised argument(s): encoding

`

**Comment by Skhendle** [comment]
[StackOverFlow](https://stackoverflow.com/questions/10706547/add-encoding-parameter-to-logging-basicconfig), seems like there is a solution for this. Next time please specify name of file in the project that produces the issue you are writing about.
