### ISSUE TITLE
Json Response 

### ISSUE THREAD

**Issue by Skhendle** [Skhendle/GraphQL_System#3]
We need to stop converting responses in our services to JSON. It seems like the routes functionality of fastApi already converts, we are having a JSON being converted to JSON again.

**Comment by Skhendle** [comment]
@sizweludick 
Please use the HTTP response classes to further update the changes.
Snippet Examples:
![Lulu2](https://user-images.githubusercontent.com/36414340/149787909-ca243b97-8eb8-4f7d-a26f-d0607b7e1193.PNG)

![Lulu1](https://user-images.githubusercontent.com/36414340/149787967-25e11576-d197-47b7-b4fb-219fbef9c7b3.PNG)

**Comment by Skhendle** [comment]
If it passes return 201, if fail return 401 Please updates too

**Comment by sizweludick** [comment]
I have updated the changes, using your Snippet Examples.

**Comment by Skhendle** [comment]
Cool I will check i t out and update your

**Comment by Skhendle** [comment]
![raiseSizwe](https://user-images.githubusercontent.com/36414340/150676821-fbab193c-fb08-44b7-b488-3a4238eeac3b.png)
 
@sizweludick 

We do not return an HTTPException, we raise it. 

Here is an example:
![sizweExample](https://user-images.githubusercontent.com/36414340/150676895-a295e699-c808-4e79-9557-5706605cece1.png)

**Comment by sizweludick** [comment]
Okay I will change that.

**Comment by sizweludick** [comment]
I changed the return to raise

**Comment by Skhendle** [comment]
Completed
